Pandas-DataFrames and Series

Pandas

Pandas is a Python library used for data manipulation and analysis.

In [310]:
import numpy as np
import pandas as pd

## Pandas Series

A Series is a one-dimensional labeled array capable of holding data of any type.

In [311]:
data=[1,2,3,4,5]
series=pd.Series(data)
print(series)
print(type(series))

0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

In [312]:
##we can custom the index
labels=['a','b','c','d','e']
pd.Series(data,index=labels)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [313]:
##creating series with array
data=np.array([4,5,6,7,8])
pd.Series(data)

0    4
1    5
2    6
3    7
4    8
dtype: int64

In [314]:
##Creating series from dictionary elements
data={'a':1,'b':2,'c':3}
series=pd.Series(data)
print(series)

a    1
b    2
c    3
dtype: int64

## Pandas DataFrame

A DataFrame is a two-dimensional labeled data structure with rows and columns.

In [315]:
##dataframe from dictionary of lists

data={
    'Name':['Harsha','satwik','Eshwar'],
    'Age':[20,20,19],
    'City':['Srikalahasti','Hyderabad','Kurnool']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  Age          City
0  Harsha   20  Srikalahasti
1  satwik   20     Hyderabad
2  Eshwar   19       Kurnool
<class 'pandas.core.frame.DataFrame'>

In [316]:
##creating a DataFrame from list
list=[
    ['John',12,6000],
    ['Sam',15,7000],
    ['Bob',14,1300]
]
columns=['Name','Age','Salary']
df=pd.DataFrame(list,columns=columns)
df

   Name  Age  Salary
0  John   12    6000
1   Sam   15    7000
2   Bob   14    1300

In [317]:
## create a dataframe from list of dictionary
data=[
    {'Name':'Harsha','Age':20,'City':'Srikalahasti'},
    {'Name':'Satwik','Age':20,'City':'Hyderabad'},
    {'Name':'Eshwar','Age':19,'City':'Kurnool'}
]
df=pd.DataFrame(data)
print(df)
type(df)

     Name  Age          City
0  Harsha   20  Srikalahasti
1  Satwik   20     Hyderabad
2  Eshwar   19       Kurnool

pandas.core.frame.DataFrame

Selecting and Indexing of Columns

In [318]:
##Accessing data from dataframe
## create a dataframe from list of dictionary
data=[
    {'Name':'Harsha','Age':20,'City':'Srikalahasti'},
    {'Name':'Satwik','Age':20,'City':'Hyderabad'},
    {'Name':'Eshwar','Age':19,'City':'Kurnool'}
]
df=pd.DataFrame(data)
df

     Name  Age          City
0  Harsha   20  Srikalahasti
1  Satwik   20     Hyderabad
2  Eshwar   19       Kurnool

In [319]:
#Accessing there data base on there name
df['Name']

0    Harsha
1    Satwik
2    Eshwar
Name: Name, dtype: object

In [320]:
##if we want to select two columns at a time we use list
df[['Name','Age']]

     Name  Age
0  Harsha   20
1  Satwik   20
2  Eshwar   19

## Selecting rows

loc-

loc is used to select data from a DataFrame using row and column labels.

🔹 Syntax
df.loc[row_label, column_label]

loc → label-based

iloc → index-based

🔹 Select Multiple Rows
df.loc[0:1]


Important:

In loc, slicing is inclusive

0:1 includes both 0 and 1

In [321]:
df

     Name  Age          City
0  Harsha   20  Srikalahasti
1  Satwik   20     Hyderabad
2  Eshwar   19       Kurnool

In [322]:
## for accessing the elements at first row we use loc
df.loc[0]

Name          Harsha
Age               20
City    Srikalahasti
Name: 0, dtype: object

In [323]:
## to access multiple rows
df.loc[[0,1]]

     Name  Age          City
0  Harsha   20  Srikalahasti
1  Satwik   20     Hyderabad

In [324]:
df.iloc[1]

Name       Satwik
Age            20
City    Hyderabad
Name: 1, dtype: object

In [325]:
df.loc[0][0]

C:\Users\prave\AppData\Local\Temp\ipykernel_7092\2527876973.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.loc[0][0]

'Harsha'

In [326]:
df.iloc[0][1]

C:\Users\prave\AppData\Local\Temp\ipykernel_7092\2309508539.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]

np.int64(20)

In [327]:
##Accessing a specified using iat
df.iat[2,2]

'Kurnool'

In [328]:
##Accessing a specified element
df.at[2,'Age']

np.int64(19)

In [331]:
df.at[2,'Name']

'Eshwar'

## Selecting Subsets of Rows and Columns

In [329]:
df.loc[[0,1]][['City','Age']]

           City  Age
0  Srikalahasti   20
1     Hyderabad   20

In [330]:
df.loc[[1,2]][['Name','Age']]

     Name  Age
1  Satwik   20
2  Eshwar   19

## Conditional Selection

In [332]:
df

     Name  Age          City
0  Harsha   20  Srikalahasti
1  Satwik   20     Hyderabad
2  Eshwar   19       Kurnool

In [333]:
df.loc[len(df)]=['Kushal',35,'Chennai']

In [334]:
df

     Name  Age          City
0  Harsha   20  Srikalahasti
1  Satwik   20     Hyderabad
2  Eshwar   19       Kurnool
3  Kushal   35       Chennai

In [335]:
## only who has age grater than 19
df[df['Age']>19]

     Name  Age          City
0  Harsha   20  Srikalahasti
1  Satwik   20     Hyderabad
3  Kushal   35       Chennai

In [336]:
##age is above 30 and there city is Chennai
df[(df['Age']>20) & (df['City']=='Chennai')]

     Name  Age     City
3  Kushal   35  Chennai

Creating a new Column

In [337]:
data=[
    {'Name':'Harsha','Age':20,'City':'Srikalahasti'},
    {'Name':'Satwik','Age':20,'City':'Hyderabad'},
    {'Name':'Eshwar','Age':19,'City':'Kurnool'}
]
df=pd.DataFrame(data)

In [338]:
df['Designation']=['Doctor','Director','Teacher']
df

     Name  Age          City Designation
0  Harsha   20  Srikalahasti      Doctor
1  Satwik   20     Hyderabad    Director
2  Eshwar   19       Kurnool     Teacher

In [339]:
df

     Name  Age          City Designation
0  Harsha   20  Srikalahasti      Doctor
1  Satwik   20     Hyderabad    Director
2  Eshwar   19       Kurnool     Teacher

## Removing Columns

 drop() in Pandas (Simple Definition)

drop() is used to remove rows or columns from a DataFrame.

df.drop(labels, axis)

labels → row or column name

axis=0 → remove row

axis=1 → remove column

In [340]:
df

     Name  Age          City Designation
0  Harsha   20  Srikalahasti      Doctor
1  Satwik   20     Hyderabad    Director
2  Eshwar   19       Kurnool     Teacher

In [341]:
#remove a column
df.drop('Designation',axis=1)

     Name  Age          City
0  Harsha   20  Srikalahasti
1  Satwik   20     Hyderabad
2  Eshwar   19       Kurnool

In [342]:
df

     Name  Age          City Designation
0  Harsha   20  Srikalahasti      Doctor
1  Satwik   20     Hyderabad    Director
2  Eshwar   19       Kurnool     Teacher

🔹Permanent Deletion

By default, drop does not change original DataFrame.

To make it permanent:

df.drop(label, axis, inplace=True)

In [343]:
df.drop('Designation',axis=1,inplace=True)

In [344]:
df

     Name  Age          City
0  Harsha   20  Srikalahasti
1  Satwik   20     Hyderabad
2  Eshwar   19       Kurnool

deleting multiple columns

In [345]:
df.drop(['City','Age'],axis=1)

     Name
0  Harsha
1  Satwik
2  Eshwar

to delete rows in the data frame

In [346]:
df

     Name  Age          City
0  Harsha   20  Srikalahasti
1  Satwik   20     Hyderabad
2  Eshwar   19       Kurnool

In [347]:
df.drop(0)

     Name  Age       City
1  Satwik   20  Hyderabad
2  Eshwar   19    Kurnool

In [348]:
df

     Name  Age          City
0  Harsha   20  Srikalahasti
1  Satwik   20     Hyderabad
2  Eshwar   19       Kurnool

In [349]:
## to delete the rows permanently
df.drop(0,inplace=True)

In [350]:
df

     Name  Age       City
1  Satwik   20  Hyderabad
2  Eshwar   19    Kurnool

## Missing Data

In [351]:
data = {
    'A': [10, 20, np.nan, 40, 50, np.nan, 70, 80],
    'B': [np.nan, 22, 33, np.nan, 55, 66, 77, np.nan],
    'C': [5, np.nan, 15, 20, np.nan, 30, 35, 40],
    'D': [np.nan, np.nan, 12, 18, 24, np.nan, 36, 42],
    'E': [1, 2, 3, np.nan, 5, 6, np.nan, 8]
}
df=pd.DataFrame(data)
df

      A     B     C     D    E
0  10.0   NaN   5.0   NaN  1.0
1  20.0  22.0   NaN   NaN  2.0
2   NaN  33.0  15.0  12.0  3.0
3  40.0   NaN  20.0  18.0  NaN
4  50.0  55.0   NaN  24.0  5.0
5   NaN  66.0  30.0   NaN  6.0
6  70.0  77.0  35.0  36.0  NaN
7  80.0   NaN  40.0  42.0  8.0

In [352]:
## to find the null values we use isna()-if it is null showa True else shows False
df.isna()

       A      B      C      D      E
0  False   True  False   True  False
1  False  False   True   True  False
2   True  False  False  False  False
3  False   True  False  False   True
4  False  False   True  False  False
5   True  False  False   True  False
6  False  False  False  False   True
7  False   True  False  False  False

In [353]:
df.isna().sum()

A    2
B    3
C    2
D    3
E    2
dtype: int64

What does any() do?

any() returns True if at least one value is True.

If all values are False → it returns False.

In [354]:
df.isna().any()

A    True
B    True
C    True
D    True
E    True
dtype: bool

Removing Missing Data

In [355]:
df

      A     B     C     D    E
0  10.0   NaN   5.0   NaN  1.0
1  20.0  22.0   NaN   NaN  2.0
2   NaN  33.0  15.0  12.0  3.0
3  40.0   NaN  20.0  18.0  NaN
4  50.0  55.0   NaN  24.0  5.0
5   NaN  66.0  30.0   NaN  6.0
6  70.0  77.0  35.0  36.0  NaN
7  80.0   NaN  40.0  42.0  8.0

In [356]:
## If a row contains at least one NaN value, the entire row will be removed.
df.dropna()

Empty DataFrame
Columns: [A, B, C, D, E]
Index: []

In [357]:
df

      A     B     C     D    E
0  10.0   NaN   5.0   NaN  1.0
1  20.0  22.0   NaN   NaN  2.0
2   NaN  33.0  15.0  12.0  3.0
3  40.0   NaN  20.0  18.0  NaN
4  50.0  55.0   NaN  24.0  5.0
5   NaN  66.0  30.0   NaN  6.0
6  70.0  77.0  35.0  36.0  NaN
7  80.0   NaN  40.0  42.0  8.0

In [358]:
## thresh = minimum number of non-NaN values required
df.dropna(thresh=4)

      A     B     C     D    E
2   NaN  33.0  15.0  12.0  3.0
4  50.0  55.0   NaN  24.0  5.0
6  70.0  77.0  35.0  36.0  NaN
7  80.0   NaN  40.0  42.0  8.0

Filling the missing data

In [359]:
df

      A     B     C     D    E
0  10.0   NaN   5.0   NaN  1.0
1  20.0  22.0   NaN   NaN  2.0
2   NaN  33.0  15.0  12.0  3.0
3  40.0   NaN  20.0  18.0  NaN
4  50.0  55.0   NaN  24.0  5.0
5   NaN  66.0  30.0   NaN  6.0
6  70.0  77.0  35.0  36.0  NaN
7  80.0   NaN  40.0  42.0  8.0

In [360]:
df.fillna(0)

      A     B     C     D    E
0  10.0   0.0   5.0   0.0  1.0
1  20.0  22.0   0.0   0.0  2.0
2   0.0  33.0  15.0  12.0  3.0
3  40.0   0.0  20.0  18.0  0.0
4  50.0  55.0   0.0  24.0  5.0
5   0.0  66.0  30.0   0.0  6.0
6  70.0  77.0  35.0  36.0  0.0
7  80.0   0.0  40.0  42.0  8.0

In [361]:
## the original data is not changed because we didn't do inpalce is true
df

      A     B     C     D    E
0  10.0   NaN   5.0   NaN  1.0
1  20.0  22.0   NaN   NaN  2.0
2   NaN  33.0  15.0  12.0  3.0
3  40.0   NaN  20.0  18.0  NaN
4  50.0  55.0   NaN  24.0  5.0
5   NaN  66.0  30.0   NaN  6.0
6  70.0  77.0  35.0  36.0  NaN
7  80.0   NaN  40.0  42.0  8.0

In [362]:
updated={'A':df['A'].mean(),'B':12,'C':12,'D':120,'E':df['E'].median()}
df.fillna(value=updated)

      A     B     C      D    E
0  10.0  12.0   5.0  120.0  1.0
1  20.0  22.0  12.0  120.0  2.0
2  45.0  33.0  15.0   12.0  3.0
3  40.0  12.0  20.0   18.0  4.0
4  50.0  55.0  12.0   24.0  5.0
5  45.0  66.0  30.0  120.0  6.0
6  70.0  77.0  35.0   36.0  4.0
7  80.0  12.0  40.0   42.0  8.0

## Merging

In [363]:
import pandas as pd

# DataFrame 1: Student information
students = pd.DataFrame({
    'student_id': [101, 102, 103, 104, 105, 106],
    'name': ['Amit', 'Neha', 'Rohit', 'Kavya', 'Vikas', 'Sara'],
    'course': ['AI', 'Data Science', 'Cyber Security', 'AI', 'Cloud Computing', 'Data Science']
})

print(students)


# DataFrame 2: Marks information
marks = pd.DataFrame({
    'student_id': [101, 102, 104, 105, 107],
    'math': [85, 78, 88, 76, 90],
    'python': [92, 81, 91, 80, 89],
    'statistics': [79, 85, 84, 82, 88]
})

print(marks)

   student_id   name           course
0         101   Amit               AI
1         102   Neha     Data Science
2         103  Rohit   Cyber Security
3         104  Kavya               AI
4         105  Vikas  Cloud Computing
5         106   Sara     Data Science
   student_id  math  python  statistics
0         101    85      92          79
1         102    78      81          85
2         104    88      91          84
3         105    76      80          82
4         107    90      89          88

In [364]:
df=pd.merge(students,marks,on='student_id',how='inner')
df

   student_id   name           course  math  python  statistics
0         101   Amit               AI    85      92          79
1         102   Neha     Data Science    78      81          85
2         104  Kavya               AI    88      91          84
3         105  Vikas  Cloud Computing    76      80          82

In [365]:
pd.merge(students,marks,on='student_id',how='outer')

   student_id   name           course  math  python  statistics
0         101   Amit               AI  85.0    92.0        79.0
1         102   Neha     Data Science  78.0    81.0        85.0
2         103  Rohit   Cyber Security   NaN     NaN         NaN
3         104  Kavya               AI  88.0    91.0        84.0
4         105  Vikas  Cloud Computing  76.0    80.0        82.0
5         106   Sara     Data Science   NaN     NaN         NaN
6         107    NaN              NaN  90.0    89.0        88.0

In [366]:
pd.merge(students,marks,on='student_id',how='left')

   student_id   name           course  math  python  statistics
0         101   Amit               AI  85.0    92.0        79.0
1         102   Neha     Data Science  78.0    81.0        85.0
2         103  Rohit   Cyber Security   NaN     NaN         NaN
3         104  Kavya               AI  88.0    91.0        84.0
4         105  Vikas  Cloud Computing  76.0    80.0        82.0
5         106   Sara     Data Science   NaN     NaN         NaN

In [367]:
pd.merge(students,marks,on='student_id',how='right')

   student_id   name           course  math  python  statistics
0         101   Amit               AI    85      92          79
1         102   Neha     Data Science    78      81          85
2         104  Kavya               AI    88      91          84
3         105  Vikas  Cloud Computing    76      80          82
4         107    NaN              NaN    90      89          88

In [368]:
df=pd.read_csv(r'C:\Users\prave\OneDrive\Documents\ml\Libaries\pandas\online_sales_dataset.csv')
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium

Concatination

In [369]:
import pandas as pd
# DataFrame 1
df1 = pd.DataFrame({
    'A': ['A1', 'A2', 'A3'],
    'B': ['B1', 'B2', 'B3'],
    'C': ['C1', 'C2', 'C3']
})
print(df1)
# DataFrame 2
df2 = pd.DataFrame({
    'A': ['A4', 'A5', 'A6'],
    'B': ['B4', 'B5', 'B6'],
    'D': ['D4', 'D5', 'D6']
})

print(df2)

    A   B   C
0  A1  B1  C1
1  A2  B2  C2
2  A3  B3  C3
    A   B   D
0  A4  B4  D4
1  A5  B5  D5
2  A6  B6  D6

In [370]:
pd.concat([df1,df2])

    A   B    C    D
0  A1  B1   C1  NaN
1  A2  B2   C2  NaN
2  A3  B3   C3  NaN
0  A4  B4  NaN   D4
1  A5  B5  NaN   D5
2  A6  B6  NaN   D6

In [371]:
pd.concat([df1,df2],axis=1)

    A   B   C   A   B   D
0  A1  B1  C1  A4  B4  D4
1  A2  B2  C2  A5  B5  D5
2  A3  B3  C3  A6  B6  D6

join the dataframes

In [372]:
import pandas as pd

# DataFrame 1:
students = pd.DataFrame({
    'name': ['Rahul', 'Anita', 'Karan', 'Megha'],
    'course': ['AI', 'Data Science', 'Cyber Security', 'Cloud']
}, index=[101, 102, 103, 104])

print(students)


# DataFrame 2
scores = pd.DataFrame({
    'math': [85, 90, 78, 88],
    'python': [92, 87, 80, 91]
}, index=[101, 102, 104, 105])

print(scores)

      name          course
101  Rahul              AI
102  Anita    Data Science
103  Karan  Cyber Security
104  Megha           Cloud
     math  python
101    85      92
102    90      87
104    78      80
105    88      91

In [373]:
students.join(scores,how='outer')

      name          course  math  python
101  Rahul              AI  85.0    92.0
102  Anita    Data Science  90.0    87.0
103  Karan  Cyber Security   NaN     NaN
104  Megha           Cloud  78.0    80.0
105    NaN             NaN  88.0    91.0

In [374]:
students.join(scores,how='inner')

      name        course  math  python
101  Rahul            AI    85      92
102  Anita  Data Science    90      87
104  Megha         Cloud    78      80

In [375]:
students.join(scores,how='left')

      name          course  math  python
101  Rahul              AI  85.0    92.0
102  Anita    Data Science  90.0    87.0
103  Karan  Cyber Security   NaN     NaN
104  Megha           Cloud  78.0    80.0

In [376]:
students.join(scores,how='right')

      name        course  math  python
101  Rahul            AI    85      92
102  Anita  Data Science    90      87
104  Megha         Cloud    78      80
105    NaN           NaN    88      91

## Group By

groupby() 

– Definition

groupby() is a Pandas function used to split the data into groups based on one or more columns so that you can perform operations on each group separately.

In [377]:
import pandas as pd

data = {
    'Category': ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing', 'Electronics', 'Furniture', 'Clothing'],
    'Store': ['S1', 'S1', 'S2', 'S1', 'S2', 'S3', 'S2', 'S3'],
    'Sales': [500, 300, 450, 700, 350, 600, 650, 400],
    'Quantity': [5, 3, 4, 7, 3, 6, 6, 4],
    'Date': pd.date_range('2023-02-01', periods=8)
}

df = pd.DataFrame(data)
df

      Category Store  Sales  Quantity       Date
0  Electronics    S1    500         5 2023-02-01
1     Clothing    S1    300         3 2023-02-02
2  Electronics    S2    450         4 2023-02-03
3    Furniture    S1    700         7 2023-02-04
4     Clothing    S2    350         3 2023-02-05
5  Electronics    S3    600         6 2023-02-06
6    Furniture    S2    650         6 2023-02-07
7     Clothing    S3    400         4 2023-02-08

In [378]:
## group by category and find the sum of the sales
df.groupby('Category')['Sales'].sum()

Category
Clothing       1050
Electronics    1550
Furniture      1350
Name: Sales, dtype: int64

In [379]:
## group by Store and find the sum of the sales
df.groupby('Store')['Sales'].sum()

Store
S1    1500
S2    1450
S3    1000
Name: Sales, dtype: int64

In [380]:
## group by multiple columns
## group by Category and Store
df.groupby(['Category','Store'])['Sales'].sum()

Category     Store
Clothing     S1       300
             S2       350
             S3       400
Electronics  S1       500
             S2       450
             S3       600
Furniture    S1       700
             S2       650
Name: Sales, dtype: int64

Aggregation

aggregate() / agg() 

– Definition

aggregate() (or agg()) is used to apply one or more statistical functions to grouped data.

In [381]:
df['Sales'].median()

475.0

In [382]:
df['Quantity'].mean()

np.float64(4.75)

In [383]:
df['Quantity'].mode()

0    3
1    4
2    6
Name: Quantity, dtype: int64

In [384]:
df['Sales'].std()

145.00615750472707

In [385]:
df['Sales'].agg(['mean','median','std','min','max','count'])

mean      493.750000
median    475.000000
std       145.006158
min       300.000000
max       700.000000
count       8.000000
Name: Sales, dtype: float64

## pivoit table

A pivot table is a data summarization tool used to organize, group, and aggregate data in order to analyze relationships and patterns in a dataset.

In [386]:
import pandas as pd
import numpy as np

data = {
    'Date': pd.date_range("2023-03-01", periods=20),
    'Product': ['Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone',
                'Tablet', 'Laptop', 'Phone', 'Tablet', 'Laptop',
                'Phone', 'Tablet', 'Laptop', 'Phone', 'Tablet',
                'Laptop', 'Phone', 'Tablet', 'Laptop', 'Phone'],
    
    'Region': ['North', 'South', 'East', 'West', 'North',
               'South', 'East', 'West', 'North', 'South',
               'East', 'West', 'North', 'South', 'East',
               'West', 'North', 'South', 'East', 'West'],
    
    'Sales': np.random.randint(500, 5000, 20),
    'Units': np.random.randint(1, 50, 20),
    
    'Salesperson': ['Ravi', 'Priya', 'Amit', 'Neha', 'Ravi',
                    'Priya', 'Amit', 'Neha', 'Ravi', 'Priya',
                    'Amit', 'Neha', 'Ravi', 'Priya', 'Amit',
                    'Neha', 'Ravi', 'Priya', 'Amit', 'Neha']
}

df = pd.DataFrame(data)

df['Month'] = df['Date'].dt.month_name()
df['Quarter'] = "Q" + df['Date'].dt.quarter.astype(str)

df

         Date Product Region  Sales  Units Salesperson  Month Quarter
0  2023-03-01  Laptop  North   3916     18        Ravi  March      Q1
1  2023-03-02   Phone  South   4486     32       Priya  March      Q1
2  2023-03-03  Tablet   East   1825     21        Amit  March      Q1
3  2023-03-04  Laptop   West   3180      7        Neha  March      Q1
4  2023-03-05   Phone  North   4531     25        Ravi  March      Q1
5  2023-03-06  Tablet  South    604      4       Priya  March      Q1
6  2023-03-07  Laptop   East   4616     23        Amit  March      Q1
7  2023-03-08   Phone   West    531     47        Neha  March      Q1
8  2023-03-09  Tablet  North   1849     44        Ravi  March      Q1
9  2023-03-10  Laptop  South   1395      4       Priya  March      Q1
10 2023-03-11   Phone   East   4417     49        Amit  March      Q1
11 2023-03-12  Tablet   West   1902     26        Neha  March      Q1
12 2023-03-13  Laptop  North   4954     21        Ravi  March      Q1
13 2023-03-14   Phone  South    714     30       Priya  March      Q1
14 2023-03-15  Tablet   East    912     47        Amit  March      Q1
15 2023-03-16  Laptop   West   3948      9        Neha  March      Q1
16 2023-03-17   Phone  North   2583     13        Ravi  March      Q1
17 2023-03-18  Tablet  South   4495     26       Priya  March      Q1
18 2023-03-19  Laptop   East   4304     21        Amit  March      Q1
19 2023-03-20   Phone   West    669     21        Neha  March      Q1

In [387]:
pd.pivot_table(df,values='Sales',index='Region',columns='Product',aggfunc='median')

Product  Laptop   Phone  Tablet
Region
East     4460.0  4417.0  1368.5
North    4435.0  3557.0  1849.0
South    1395.0  2600.0  2549.5
West     3564.0   600.0  1902.0

In [388]:
pd.pivot_table(df,values=['Sales','Units'],index='Region',columns='Product')

          Sales                  Units
Product  Laptop   Phone  Tablet Laptop Phone Tablet
Region
East     4460.0  4417.0  1368.5   22.0  49.0   34.0
North    4435.0  3557.0  1849.0   19.5  19.0   44.0
South    1395.0  2600.0  2549.5    4.0  31.0   15.0
West     3564.0   600.0  1902.0    8.0  34.0   26.0

Pivot tables are mainly designed for numeric columns

Cross Table

In [389]:
pd.crosstab(df['Region'],df['Product'],)

Product  Laptop  Phone  Tablet
Region
East          2      1       2
North         2      2       1
South         1      2       2
West          2      2       1

## Renaming Columns

In [390]:
df

         Date Product Region  Sales  Units Salesperson  Month Quarter
0  2023-03-01  Laptop  North   3916     18        Ravi  March      Q1
1  2023-03-02   Phone  South   4486     32       Priya  March      Q1
2  2023-03-03  Tablet   East   1825     21        Amit  March      Q1
3  2023-03-04  Laptop   West   3180      7        Neha  March      Q1
4  2023-03-05   Phone  North   4531     25        Ravi  March      Q1
5  2023-03-06  Tablet  South    604      4       Priya  March      Q1
6  2023-03-07  Laptop   East   4616     23        Amit  March      Q1
7  2023-03-08   Phone   West    531     47        Neha  March      Q1
8  2023-03-09  Tablet  North   1849     44        Ravi  March      Q1
9  2023-03-10  Laptop  South   1395      4       Priya  March      Q1
10 2023-03-11   Phone   East   4417     49        Amit  March      Q1
11 2023-03-12  Tablet   West   1902     26        Neha  March      Q1
12 2023-03-13  Laptop  North   4954     21        Ravi  March      Q1
13 2023-03-14   Phone  South    714     30       Priya  March      Q1
14 2023-03-15  Tablet   East    912     47        Amit  March      Q1
15 2023-03-16  Laptop   West   3948      9        Neha  March      Q1
16 2023-03-17   Phone  North   2583     13        Ravi  March      Q1
17 2023-03-18  Tablet  South   4495     26       Priya  March      Q1
18 2023-03-19  Laptop   East   4304     21        Amit  March      Q1
19 2023-03-20   Phone   West    669     21        Neha  March      Q1

In [391]:
## if we want to change the column name we use rename function
df.rename(columns={'Units':'Unit_stock'})
#we can also do same for multiple columns as it is an dictionary

         Date Product Region  Sales  Unit_stock Salesperson  Month Quarter
0  2023-03-01  Laptop  North   3916          18        Ravi  March      Q1
1  2023-03-02   Phone  South   4486          32       Priya  March      Q1
2  2023-03-03  Tablet   East   1825          21        Amit  March      Q1
3  2023-03-04  Laptop   West   3180           7        Neha  March      Q1
4  2023-03-05   Phone  North   4531          25        Ravi  March      Q1
5  2023-03-06  Tablet  South    604           4       Priya  March      Q1
6  2023-03-07  Laptop   East   4616          23        Amit  March      Q1
7  2023-03-08   Phone   West    531          47        Neha  March      Q1
8  2023-03-09  Tablet  North   1849          44        Ravi  March      Q1
9  2023-03-10  Laptop  South   1395           4       Priya  March      Q1
10 2023-03-11   Phone   East   4417          49        Amit  March      Q1
11 2023-03-12  Tablet   West   1902          26        Neha  March      Q1
12 2023-03-13  Laptop  North   4954          21        Ravi  March      Q1
13 2023-03-14   Phone  South    714          30       Priya  March      Q1
14 2023-03-15  Tablet   East    912          47        Amit  March      Q1
15 2023-03-16  Laptop   West   3948           9        Neha  March      Q1
16 2023-03-17   Phone  North   2583          13        Ravi  March      Q1
17 2023-03-18  Tablet  South   4495          26       Priya  March      Q1
18 2023-03-19  Laptop   East   4304          21        Amit  March      Q1
19 2023-03-20   Phone   West    669          21        Neha  March      Q1

## Extra
Some date related inbuilt functions

| Function      | Meaning |
| ------------- | ------- |
| `.dt.year`    | year    |
| `.dt.month`   | month   |
| `.dt.day`     | day     |
| `.dt.quarter` | quarter |

## Operations

In [392]:
df=pd.DataFrame({
    'A': [2, 4, 6, 8, 10],
    'B': [5, 15, 25, 35, 45],
    'C': [50, 100, 150, 200, 250]
})
df

    A   B    C
0   2   5   50
1   4  15  100
2   6  25  150
3   8  35  200
4  10  45  250

In [393]:
df.shape

(5, 3)

In [394]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [395]:
df['A']+3

0     5
1     7
2     9
3    11
4    13
Name: A, dtype: int64

Applying Functions

In [396]:
def square(x):
    return x*x
df['B']=df['B'].apply(square)

In [397]:
df

    A     B    C
0   2    25   50
1   4   225  100
2   6   625  150
3   8  1225  200
4  10  2025  250

In [398]:
df['C'].apply(
    lambda x:x+2
)

0     52
1    102
2    152
3    202
4    252
Name: C, dtype: int64

dtypes in Pandas (Simple Definition)

dtypes is used to check the data type of each column in a DataFrame.

In [399]:
df.dtypes

A    int64
B    int64
C    int64
dtype: object

info() in Pandas

Definition

info() is used to get a summary of the DataFrame structure.

In [400]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       5 non-null      int64
 1   B       5 non-null      int64
 2   C       5 non-null      int64
dtypes: int64(3)
memory usage: 252.0 bytes

describe() in Pandas

Definition

describe() gives statistical summary of numerical columns.

In [401]:
df.describe

<bound method NDFrame.describe of     A     B    C
0   2    25   50
1   4   225  100
2   6   625  150
3   8  1225  200
4  10  2025  250>

## Example

A example by using pandas to large datset

In [402]:
import pandas as pd

In [403]:
df=pd.read_csv("online_sales_dataset.csv")
##fetch the first five rows
df.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium

In [404]:
df.tail()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
49777,354083,SKU_1562,Blue Pen,25,2025-09-05 01:00,70.92,51445.0,Spain,0.20,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium
49778,296698,SKU_1930,USB Cable,7,2025-09-05 02:00,51.74,28879.0,United States,0.23,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low
49779,177622,SKU_1766,Office Chair,43,2025-09-05 03:00,85.25,21825.0,Portugal,0.20,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High
49780,701213,SKU_1602,Notebook,48,2025-09-05 04:00,39.64,43199.0,United Kingdom,0.31,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium
49781,772215,SKU_1832,White Mug,30,2025-09-05 05:00,38.27,53328.0,France,0.10,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low

In [405]:
df.describe()

,InvoiceNo,Quantity,UnitPrice,CustomerID,Discount,ShippingCost
count,49782.000000,49782.000000,49782.000000,44804.000000,49782.000000,47293.000000
mean,550681.239946,22.372343,47.537862,55032.871775,0.275748,17.494529
std,260703.009944,17.917774,33.479510,25913.660157,0.230077,7.220557
min,100005.000000,-50.000000,-99.980000,10001.000000,0.000000,5.000000
25%,324543.000000,11.000000,23.592500,32750.750000,0.130000,11.220000
50%,552244.000000,23.000000,48.920000,55165.000000,0.260000,17.500000
75%,776364.000000,37.000000,74.610000,77306.250000,0.380000,23.720000
max,999997.000000,49.000000,100.000000,99998.000000,1.999764,30.000000

In [406]:
df.dtypes

InvoiceNo              int64
StockCode             object
Description           object
Quantity               int64
InvoiceDate           object
UnitPrice            float64
CustomerID           float64
Country               object
Discount             float64
PaymentMethod         object
ShippingCost         float64
Category              object
SalesChannel          object
ReturnStatus          object
ShipmentProvider      object
WarehouseLocation     object
OrderPriority         object
dtype: object

In [407]:
df['InvoiceDate']=pd.to_datetime(df['InvoiceDate'])

In [408]:
df.dtypes

InvoiceNo                     int64
StockCode                    object
Description                  object
Quantity                      int64
InvoiceDate          datetime64[ns]
UnitPrice                   float64
CustomerID                  float64
Country                      object
Discount                    float64
PaymentMethod                object
ShippingCost                float64
Category                     object
SalesChannel                 object
ReturnStatus                 object
ShipmentProvider             object
WarehouseLocation            object
OrderPriority                object
dtype: object

In [409]:
df.isna()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,True,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49778,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49779,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49780,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
49781,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [410]:
#if there any missing values are present in the column
df.isna().any()

InvoiceNo            False
StockCode            False
Description          False
Quantity             False
InvoiceDate          False
UnitPrice            False
CustomerID            True
Country              False
Discount             False
PaymentMethod        False
ShippingCost          True
Category             False
SalesChannel         False
ReturnStatus         False
ShipmentProvider     False
WarehouseLocation     True
OrderPriority        False
dtype: bool

In [411]:
df.isna().sum()

InvoiceNo               0
StockCode               0
Description             0
Quantity                0
InvoiceDate             0
UnitPrice               0
CustomerID           4978
Country                 0
Discount                0
PaymentMethod           0
ShippingCost         2489
Category                0
SalesChannel            0
ReturnStatus            0
ShipmentProvider        0
WarehouseLocation    3485
OrderPriority           0
dtype: int64

In [412]:
#we can fill with any specific value
df_filled=df.fillna(0)

In [413]:
#filling missing values with mean of the column
df['Shipping_fillNA']=df['ShippingCost'].fillna(df['ShippingCost'].mean())

In [414]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority,Shipping_fillNA
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium,10.790000
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium,9.510000
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High,23.030000
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low,11.080000
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium,17.494529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,2025-09-05 01:00:00,70.92,51445.0,Spain,0.200000,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium,8.960000
49778,296698,SKU_1930,USB Cable,7,2025-09-05 02:00:00,51.74,28879.0,United States,0.230000,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low,23.550000
49779,177622,SKU_1766,Office Chair,43,2025-09-05 03:00:00,85.25,21825.0,Portugal,0.200000,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High,16.260000
49780,701213,SKU_1602,Notebook,48,2025-09-05 04:00:00,39.64,43199.0,United Kingdom,0.310000,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium,28.560000
49781,772215,SKU_1832,White Mug,30,2025-09-05 05:00:00,38.27,53328.0,France,0.100000,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low,9.130000

In [415]:
df.dtypes

InvoiceNo                     int64
StockCode                    object
Description                  object
Quantity                      int64
InvoiceDate          datetime64[ns]
UnitPrice                   float64
CustomerID                  float64
Country                      object
Discount                    float64
PaymentMethod                object
ShippingCost                float64
Category                     object
SalesChannel                 object
ReturnStatus                 object
ShipmentProvider             object
WarehouseLocation            object
OrderPriority                object
Shipping_fillNA             float64
dtype: object

In [416]:
##Renaming the columns
df.rename(columns={'StockCode':'Code'})

,InvoiceNo,Code,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority,Shipping_fillNA
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium,10.790000
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium,9.510000
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High,23.030000
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low,11.080000
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium,17.494529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,2025-09-05 01:00:00,70.92,51445.0,Spain,0.200000,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium,8.960000
49778,296698,SKU_1930,USB Cable,7,2025-09-05 02:00:00,51.74,28879.0,United States,0.230000,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low,23.550000
49779,177622,SKU_1766,Office Chair,43,2025-09-05 03:00:00,85.25,21825.0,Portugal,0.200000,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High,16.260000
49780,701213,SKU_1602,Notebook,48,2025-09-05 04:00:00,39.64,43199.0,United Kingdom,0.310000,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium,28.560000
49781,772215,SKU_1832,White Mug,30,2025-09-05 05:00:00,38.27,53328.0,France,0.100000,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low,9.130000

in creating an new column with the column present in the data check that there should not any missing values

In [417]:
##change datatypes
df['UnitPrice_new']=df['UnitPrice'].astype(int)
df.dtypes

InvoiceNo                     int64
StockCode                    object
Description                  object
Quantity                      int64
InvoiceDate          datetime64[ns]
UnitPrice                   float64
CustomerID                  float64
Country                      object
Discount                    float64
PaymentMethod                object
ShippingCost                float64
Category                     object
SalesChannel                 object
ReturnStatus                 object
ShipmentProvider             object
WarehouseLocation            object
OrderPriority                object
Shipping_fillNA             float64
UnitPrice_new                 int64
dtype: object

In [418]:
df['NewUnitPrice']=df['UnitPrice'].apply(lambda x:x*2)

In [419]:
df

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Discount,PaymentMethod,ShippingCost,Category,SalesChannel,ReturnStatus,ShipmentProvider,WarehouseLocation,OrderPriority,Shipping_fillNA,UnitPrice_new,NewUnitPrice
0,221958,SKU_1964,White Mug,38,2020-01-01 00:00:00,1.71,37039.0,Australia,0.470000,Bank Transfer,10.79,Apparel,In-store,Not Returned,UPS,London,Medium,10.790000,1,3.42
1,771155,SKU_1241,White Mug,18,2020-01-01 01:00:00,41.25,19144.0,Spain,0.190000,paypall,9.51,Electronics,Online,Not Returned,UPS,Rome,Medium,9.510000,41,82.50
2,231932,SKU_1501,Headphones,49,2020-01-01 02:00:00,29.11,50472.0,Germany,0.350000,Bank Transfer,23.03,Electronics,Online,Returned,UPS,Berlin,High,23.030000,29,58.22
3,465838,SKU_1760,Desk Lamp,14,2020-01-01 03:00:00,76.68,96586.0,Netherlands,0.140000,paypall,11.08,Accessories,Online,Not Returned,Royal Mail,Rome,Low,11.080000,76,153.36
4,359178,SKU_1386,USB Cable,-30,2020-01-01 04:00:00,-68.11,NaN,United Kingdom,1.501433,Bank Transfer,NaN,Electronics,In-store,Not Returned,FedEx,NaN,Medium,17.494529,-68,-136.22
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49777,354083,SKU_1562,Blue Pen,25,2025-09-05 01:00:00,70.92,51445.0,Spain,0.200000,Credit Card,8.96,Electronics,Online,Returned,UPS,Berlin,Medium,8.960000,70,141.84
49778,296698,SKU_1930,USB Cable,7,2025-09-05 02:00:00,51.74,28879.0,United States,0.230000,Bank Transfer,23.55,Electronics,Online,Not Returned,FedEx,Amsterdam,Low,23.550000,51,103.48
49779,177622,SKU_1766,Office Chair,43,2025-09-05 03:00:00,85.25,21825.0,Portugal,0.200000,Bank Transfer,16.26,Furniture,In-store,Not Returned,FedEx,London,High,16.260000,85,170.50
49780,701213,SKU_1602,Notebook,48,2025-09-05 04:00:00,39.64,43199.0,United Kingdom,0.310000,paypall,28.56,Apparel,Online,Not Returned,Royal Mail,London,Medium,28.560000,39,79.28
49781,772215,SKU_1832,White Mug,30,2025-09-05 05:00:00,38.27,53328.0,France,0.100000,Credit Card,9.13,Stationery,Online,Not Returned,UPS,Rome,Low,9.130000,38,76.54

In [420]:
##Data Aggregating and grouping
grouped_by=df.groupby('SalesChannel')['UnitPrice'].mean()
print(grouped_by)

SalesChannel
In-store    47.669934
Online      47.407476
Name: UnitPrice, dtype: float64

In [421]:
df.groupby(['SalesChannel','PaymentMethod'])['Quantity'].sum()

SalesChannel  PaymentMethod
In-store      Bank Transfer    187295
              Credit Card      187170
              paypall          181212
Online        Bank Transfer    189493
              Credit Card      184606
              paypall          183964
Name: Quantity, dtype: int64

In [422]:
##check the total discount given Country 
df.groupby(['SalesChannel','Country'])['Discount'].sum()

SalesChannel  Country
In-store      Australia         533.464683
              Belgium           573.455991
              France            560.170372
              Germany           597.653512
              Italy             558.875415
              Netherlands       592.531689
              Norway            555.123175
              Portugal          562.809275
              Spain             562.131555
              Sweden            562.209427
              United Kingdom    598.275853
              United States     542.638810
Online        Australia         595.906571
              Belgium           562.329200
              France            614.184318
              Germany           563.966229
              Italy             558.928271
              Netherlands       612.580398
              Norway            577.368045
              Portugal          592.629417
              Spain             563.846260
              Sweden            573.948569
              United Kingdom    555.327619
              United States     556.915755
Name: Discount, dtype: float64

In [423]:
#now we want to calculate the total sum of the discount given
df['Discount'].sum()

np.float64(13727.270409092269)

In [424]:
##aggregate multiple functions
grouped_agg=df.groupby('Country')['Discount'].agg(['mean','sum','count'])

In [425]:
grouped_agg

                    mean          sum  count
Country
Australia       0.274786  1129.371254   4110
Belgium         0.272371  1135.785191   4170
France          0.277625  1174.354690   4230
Germany         0.277767  1161.619741   4182
Italy           0.276137  1117.803686   4048
Netherlands     0.288788  1205.112087   4173
Norway          0.272430  1132.491220   4157
Portugal        0.277550  1155.438691   4163
Spain           0.274629  1125.977815   4100
Sweden          0.269807  1136.157996   4211
United Kingdom  0.275982  1153.603472   4180
United States   0.270960  1099.554565   4058